export const EXTERNAL_REDIRECT_TOKEN_VERIFIER = Symbol(
  'EXTERNAL_REDIRECT_TOKEN_VERIFIER',
);

export interface ExternalRedirectTokenValidationResult {
  userId: string;
  applicationId: string;
  redirectRoute: string;
}

/**
 * Anti-corruption port for validating external redirect tokens generated by DevelopersConsole.
 */
export interface IExternalRedirectTokenVerifier {
  validateAndConsume(token: string): Promise<ExternalRedirectTokenValidationResult>;
}
